### ISSUE TITLE
Kodi repository submission?

### ISSUE THREAD

**Issue by Lunatixz** [add-ons/service.iptv.manager#47]
@dagwieers any plans to submit this to the Kodi repository?

**Comment by dagwieers** [comment]
@michaelarnauts Are we ready for this? I am ok to release.

**Comment by dagwieers** [comment]
Let me already add a GitHub CI release workflow to make releasing super-easy.

**Comment by Lunatixz** [comment]
I recommend adding a setting to allow manual m3u/xmltv path setup, only noticed the "automatic" option.

**Comment by dagwieers** [comment]
@michaelarnauts proposed IPTV Manager to the official Kodi repository here: https://github.com/xbmc/repo-scripts/pull/1710

**Comment by michaelarnauts** [comment]
> I recommend adding a setting to allow manual m3u/xmltv path setup, only noticed the "automatic" option.
> 
> Also, https://github.com/add-ons/service.iptv.manager/blob/master/addon.xml#L4 needs to be set up for matrix, 3.0.0
> 
> Looking forward to adding support for this manager!

You can still manually configure Simple IPTV, the item in the settings is just there for convenience. It's not easy to find the exact path to use, and the settings to configure. This could be improved by using something like a `http://127.0.0.1:xxxx/epg` url, but it's easier to just write the file to the filesystem instead of having Simple IPTV fetch it trough HTTP. Also, what port should we use, what if the port is already in use, ...

We probably can change some things for Matrix, so I guess the best way forward is to maintain two branches unfortunatly.

**Comment by dagwieers** [comment]
> We probably can change some things for Matrix, so I guess the best way forward is to maintain two branches unfortunately.

As discussed, I think you can still avoid having 2 branches by making some of the Leia-specific stuff conditional. Just like we already do for Python 2/3 compatibility.

**Comment by skank01** [comment]
OH, this wont take long anymore before released in official kodi repository?

**Comment by piejanssens** [comment]
I just installed it on Leia through the repo 🎉

**Comment by dagwieers** [comment]
Yes, it is in Leia already. We will have to spend some more time before we can make it available for Matrix, as the code could look a bit different because of difference in IPTV Simple.

We also are not sure if we want to manage 2 branches (one for each) or do something else instead.
