### ISSUE TITLE
PVR IPTV dependency version

### ISSUE THREAD

**Issue by Roel** [add-ons/service.iptv.manager#52]
Hi!

Is there a specific reason for requiring version 3.9.8 of PVR IPTV Simple Client (as introduced in #42), or should it work with older versions too? I'm wondering since I'm using Kodi on Raspbian Buster which only has version 3.8.8 in the repos, and currently cannot install the add-on.

Thanks in advance!

**Comment by michaelarnauts** [comment]
Hmm, 3.8.8 should also work. I just picked the latest version since that's the one I tested with.

Although 3.9.8 (the latest release for Lei) is from February, so it probably also means you are running an older Kodi, and also an older Inputstream Adaptive. You might want to look into using a more up to date version. I think there is a apt repository with more up to date packages somewhere.

**Comment by Roel** [comment]
I have Kodi version 18.7 and Inputstream Adaptive version 2.4.4, not sure how old they are (but working fine). The Kodi [installation guide](https://kodi.wiki/view/HOW-TO:Install_Kodi_on_Raspberry_Pi#Raspberry_Pi_OS) for Raspbian also uses the standard repos, but I'm happy to add/switch to another repo providing more recent stable versions for ARM.

**Comment by michaelarnauts** [comment]
@Roel @MPParsley A new version has been released that will fix this issue. It will be available in the Kodi repo's within a few days, or you can install it directly from a ZIP by downloading it here: https://github.com/add-ons/service.iptv.manager/releases/tag/v0.2.2

**Comment by Roel** [comment]
Thanks!

**Comment by MPParsley** [comment]
Thanks and great addon!

Note that I had to restart my Pi in order for it to work (IPTV Simple kept shutting down).
